import copy
from typing import Literal, Optional

import numpy as np

from CADETProcess.processModel import (
    ChromatographicColumnBase,
    ComponentSystem,
    Cstr,
    FlowSheet,
)


class ZRMFlowSheetBuilder:
    """
    Zonal rate model flow sheet builder.

    Flow sheet builder for compartmentalized membrane chromatography device.

    Attributes
    ----------
    configuration : str
        Configuration type (e.g., 'axial', 'radial').
    zone_template : Literal[Cstr, ChromatographicColumnBase]
        Template for the zones.
    segments_area : list[float]
        List of surface areas of the segmented membrane zones.
    void_in_volumes : list[float]
        List of inlet void volumes.
    void_out_volumes : Optional[list[float]]
        List of outlet void volumes.
    """

    def __init__(
        self,
        configuration: Literal["axial", "radial"],
        zone_template: Literal[Cstr, ChromatographicColumnBase],
        segments_area: list[float],
        void_in_volumes: float | list[float],
        void_out_volumes: Optional[float | list[float]] = None,
        name: str = "",
    ) -> None:
        """
        Initialize the ZRMBuilder.

        Parameters
        ----------
        configuration : str
            Configuration type (e.g., 'axial', 'radial').
        zone_template : Literal[Cstr, ChromatographicColumnBase]
            Template for the zones.
        segments_area : list[float]
            Surface areas of the segmented membrane zones.
        void_in_volumes : float | list[float]
            List of inlet void volumes.
            If scalar value is provided, the total volume is split by the
            number of zones.
        void_out_volumes : Optional[float | list[float]]
            List of outlet void volumes.
            If scalar value is provided, the total volume is split by the
            number of zones.
        name : str
            Optional prefix for all units generated by this builder.
            If empty, the old names are preserved:
            void_in_0, zone_0, void_out_0, ...
            If name="module_1", names become:
            module_1_void_in_0, module_1_zone_0, module_1_void_out_0, ...
        """
        self.name = name

        configuration = configuration.lower()
        if configuration not in ['axial', 'radial']:
            raise ValueError("Configuration must be either 'axial' or 'radial'")
        self.configuration = configuration

        if not isinstance(zone_template, (Cstr, ChromatographicColumnBase)):
            raise TypeError(
                "Zone template must be a Cstr or ChromatographicColumnBase"
            )
        self.zone_template = zone_template

        if any(area <= 0 for area in segments_area):
            raise ValueError("All segment areas must be positive.")
        self.segments_area = segments_area

        if np.isscalar(void_in_volumes):
            void_in_volumes = [
                void_in_volumes / self.n_zones for _ in range(self.n_zones)
            ]

        if any(volume <= 0 for volume in void_in_volumes):
            raise ValueError("All inlet cstr volumes must be positive.")
        self.void_in_volumes = void_in_volumes

        if void_out_volumes is None:
            void_out_volumes = void_in_volumes
        if np.isscalar(void_out_volumes):
            void_out_volumes = [
                void_out_volumes / self.n_zones for _ in range(self.n_zones)
            ]
        if any(volume <= 0 for volume in void_out_volumes):
            raise ValueError("All outlet cstr volumes must be positive.")
        self.void_out_volumes = void_out_volumes

    def _name(self, base: str) -> str:
        """Name of a unit with an optional prefix."""
        if self.name:
            return f"{self.name}_{base}"
        return base

    @property
    def n_zones(self) -> int:
        """int: Number of zones."""
        return len(self.segments_area)

    @property
    def component_system(self) -> ComponentSystem:
        """ComponentSystem: The component system of the zone template."""
        return self.zone_template.component_system

    @property
    def segments_ratio(self) -> list[float]:
        """Ratio of surface areas."""
        total_area = sum(self.segments_area)
        return [area / total_area for area in self.segments_area]

    @property
    def inlet_port(self) -> str:
        """Name void that acts as inlet port."""
        return self._name("void_in_0")

    @property
    def outlet_port(self) -> str:
        """Name of the void that acts as outlet port."""
        if self.configuration == "axial":
            return self._name("void_out_0")
        return self._name(f"void_out_{self.n_zones - 1}")

    def build_flow_sheet(self) -> FlowSheet:
        """
        Construct the flow sheet for the process.

        Returns
        -------
        FlowSheet
             A `FlowSheet` object representing the constructed flow system.
        """
        self.flow_sheet = FlowSheet(self.component_system)

        # Proceed with the rest of the build logic here
        self._initialize_units()
        self._connect_units()

        return self.flow_sheet

    def _initialize_units(self) -> None:
        """Initialize zones and void units in the flow sheet."""
        for i, area in enumerate(self.segments_area):
            void_in = Cstr(self.component_system, self._name(f"void_in_{i}"))
            void_in.init_liquid_volume = self.void_in_volumes[i]
            self.flow_sheet.add_unit(void_in)

            zone = copy.deepcopy(self.zone_template)
            zone.name = self._name(f'zone_{i}')
            zone.component_system = self.component_system

            is_radial = type(zone).__name__.lower().startswith("radial")

            if is_radial:
                zone.length = area
            else:
                zone.cross_section_area = area

            self.flow_sheet.add_unit(zone)

            void_out = Cstr(self.component_system, self._name(f"void_out_{i}"))
            void_out.init_liquid_volume = self.void_out_volumes[i]
            self.flow_sheet.add_unit(void_out)

    def _connect_units(self) -> None:
        """Connect all units in the flow sheet."""
        # First half of voids
        for i in range(self.n_zones - 1):
            self.flow_sheet.add_connection(
                self._name(f"void_in_{i}"), self._name(f"void_in_{i + 1}")
            )

        # Connect first half voids to zones
        for i in range(self.n_zones):
            self.flow_sheet.add_connection(
                self._name(f"void_in_{i}"), self._name(f'zone_{i}')
            )
            self.flow_sheet.add_connection(
                self._name(f'zone_{i}'), self._name(f"void_out_{i}"),
            )

        # Conditional handling for configuration
        if self.configuration == 'axial':
            # Forward connection for second void chain
            for i in range(self.n_zones - 1):
                self.flow_sheet.add_connection(
                    self._name(f"void_out_{i + 1}"), self._name(f"void_out_{i}")
                )
        elif self.configuration == 'radial':
            # Backward connection for second void chain
            for i in range(self.n_zones - 1):
                self.flow_sheet.add_connection(
                    self._name(f"void_out_{i}"), self._name(f"void_out_{i + 1}")
                )
        else:
            raise ValueError("Invalid configuration. Must be 'axial' or 'radial'.")

        # Set output states for flow splitting
        lowest_bound = 1e-12  # Prevent divide-by-zero

        for i in range(self.n_zones - 1):
            remaining_area = sum(self.segments_ratio[i:]) + lowest_bound
            zone_fraction = self.segments_ratio[i] / remaining_area
            next_cstr_fraction = 1 - zone_fraction
            self.flow_sheet.set_output_state(
                self._name(f'void_in_{i}'),
                {
                    self._name(f'void_in_{i + 1}'): next_cstr_fraction,
                    self._name(f'zone_{i}'): zone_fraction
                }
            )
